name: ns_utils
description: Set of methods/extentions for flutter that makes using framework in a much easier and clean way also adds additional functionality.
version: 0.0.4
documentation: https://github.com/ajaynonstopio/ns_utils
homepage: https://github.com/ajaynonstopio/ns_utils

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:

  #<editor-fold desc="UTILS">
  intl: ^0.17.0
  flutter_screenutil: ^4.0.3+3
  logger: ^1.0.0
  cached_network_image: ^2.5.1
  #</editor-fold>

  #<editor-fold desc="LOCAL-DATABASE">
  shared_preferences: ^2.0.5
  crossplat_objectid: 2.1.4
  #</editor-fold>

  #<editor-fold desc="DEVICE APIS">
  device_info: ^2.0.0
  package_info: ^2.0.0
  flutter_statusbarcolor: 0.2.3
  #</editor-fold>

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

